application: programadora-java-1042
version: http2
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: webapp/assets

- url: /manifest\.json
  static_files: webapp/service/manifest.json
  upload: webapp/service/manifest.json

- url: /notification\.js
  static_files: webapp/service/notification.js
  upload: webapp/service/notification.js

- url: /.*
  script: _go_app