application: programadora-java-1042
version: http2
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: webapp/assets

- url: /app
  static_dir: webapp/app

- url: /.*
  script: _go_app